/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoWrapList: typeof import('./../../src/components/AutoWrapList/index.vue')['default']
    Editor: typeof import('./../../src/components/Editor/index.vue')['default']
    IconFont: typeof import('./../../src/components/IconFont/index.vue')['default']
    InnerLink: typeof import('./../../src/components/InnerLink/index.vue')['default']
    QRCode: typeof import('./../../src/components/QRCode/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../../src/components/SvgIcon/index.vue')['default']
  }
}
